name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install wasm-tools
        run: |
          WASM_TOOLS_VERSION=1.239.0
          WASM_TOOLS_DIR="wasm-tools-${WASM_TOOLS_VERSION}-x86_64-linux"
          mkdir -p _tools
          pushd _tools
          curl -sSL "https://github.com/bytecodealliance/wasm-tools/releases/download/v${WASM_TOOLS_VERSION}/${WASM_TOOLS_DIR}.tar.gz" -o wasm-tools.tar.gz
          tar -xzf wasm-tools.tar.gz
          rm -f wasm-tools.tar.gz
          popd
          echo "$(pwd)/_tools/${WASM_TOOLS_DIR}" >> "$GITHUB_PATH"

      - name: Run tests
        run: node run-tests.js
